<?xml version="1.0"?>

<robot name="arm_hardware" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- RS405CB_DEPTH: doesn't include its back horn-->
  <property name="RS405CB_WIDTH" value="0.033" />
  <property name="RS405CB_HEIGHT" value="0.043" />
  <property name="RS405CB_DEPTH" value="0.045" />
  
  <property name="VH_6_W" value="0.03" />
  <property name="VH_6_H" value="0.045" />
  <property name="VH_6_D" value="0.054" />
  <property name="VH_5_W" value="0.032" />
  <property name="VH_5_H" value="0.032" />
  <property name="VH_5_D" value="0.047" />
  <property name="VH_4_W" value="0.032" />
  <property name="VH_4_H" value="0.032" />
  <property name="VH_4_D" value="0.047" />
  <property name="VH_3_W" value="0.022" />
  <property name="VH_3_H" value="0.037" />
  <property name="VH_3_D" value="0.055" />
  <property name="VH_2_W" value="0.032" />
  <property name="VH_2_H" value="0.032" />
  <property name="VH_2_D" value="0.047" />
  <property name="VH_1A_W" value="0.022" />
  <property name="VH_1A_H" value="0.037" />
  <property name="VH_1A_D" value="0.055" />
  <property name="VH_1B_W" value="0.032" />
  <property name="VH_1B_H" value="0.032" />
  <property name="VH_1B_D" value="0.047" />
  
  <property name="PI" value="3.14159" />
  <property name="RS405CB_MESH_SCALE" value="0.001" />
  
  <!--macro name="RS405CB_fixed" params="parent name *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}_link"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://akira_description/meshes/RS405CB.stl" scale="${RS405CB_MESH_SCALE} ${RS405CB_MESH_SCALE} ${RS405CB_MESH_SCALE}" />
        </geometry>
        <material name="Black"/>
      </visual>

       <collision>
        <origin xyz="-0.01 0.0 ${-RS405CB_DEPTH/2}" rpy="0 0 0" />
        <geometry>
          <box size="${RS405CB_HEIGHT} ${RS405CB_WIDTH} ${RS405CB_DEPTH}"/>
        </geometry>
      </collision>
    </link>
  </macro-->
  
  <macro name="RS405CB_revolute" params="parent name llimit ulimit vlimit *origin *axis">
    <joint name="${name}_joint" type="revolute">
      <xacro:insert_block name="origin" />
      <xacro:insert_block name="axis" />
      <limit effort="1.0" velocity="${vlimit}" lower="${llimit}" upper="${ulimit}" />
      <parent link="${parent}_link"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://akira_description/meshes/RS405CB.stl" scale="${RS405CB_MESH_SCALE} ${RS405CB_MESH_SCALE} ${RS405CB_MESH_SCALE}" />
	  <!--box size="${RS405CB_HEIGHT} ${RS405CB_WIDTH} ${RS405CB_DEPTH}"/-->
        </geometry>
         <material name="Black"/>
      </visual>

      <collision>
        <origin xyz="-0.01 0.0 ${-RS405CB_DEPTH/2}" rpy="0 0 0" />
        <geometry>
          <!--box size="${RS405CB_HEIGHT} ${RS405CB_WIDTH} ${RS405CB_DEPTH}"/-->
          <box size="0.001 0.001 0.001"/>
        </geometry>
      </collision>
    </link>
  </macro>
  
  <macro name="finger" params="parent name color *origin">
    <joint name="${name}_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent}_link"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <inertial>
        <mass value="0.00001" />
        <origin xyz="0 0 0" />
        <inertia ixx="1.0" ixy="0.0" ixz="0.0"
          iyy="1.0" iyz="0.0"
          izz="1.0" />
      </inertial>

      <visual>
        <origin xyz=" 0 0 0 " rpy="0 0 0" />
        <geometry>
          <mesh filename="package://akira_description/meshes/finger.stl" scale="${DYNAMIXEL_MESH_SCALE} ${DYNAMIXEL_MESH_SCALE} ${DYNAMIXEL_MESH_SCALE}"/>
        </geometry>
        <material name="${color}"/>
      </visual>

      <collision>
        <origin xyz="0.02645 0.0 -0.00655" rpy="0 0 0" />
        <geometry>
          <box size="0.0783 0.03801 0.0193"/>
        </geometry>
      </collision>
    </link>
  </macro>

</robot>

